name: thefrick
version: stable
version-script: git -C parts/thefrick/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  The Frick tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  thefrick:
    command: bin/thefrick
    environment:
        PYTHONIOENCODING: utf-8
  frick:
    command: bin/frick
    environment:
        PYTHONIOENCODING: utf-8

parts:
  thefrick:
    source: https://github.com/earboxer/thefrick.git
    plugin: python
